name: Instagram CI/CD

on:
  push:
    branches:
      - main

jobs:

  # =========================
  # CI - TEST
  # =========================
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest -v


  # =========================
  # CD - DEPLOY TO EC2
  # =========================
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/instagram-cicd

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old container..."
            docker stop instagram-app || true

            echo "Removing old container..."
            docker rm instagram-app || true

            echo "Building new Docker image..."
            docker build -t instagram-app .

            echo "Starting new container..."
            docker run -d \
              --name instagram-app \
              -p 8080:5000 \
              instagram-app

            echo "Deployment completed!"

            echo "Running containers:"
            docker ps
